printshellcmds: True
jobs: 158
executor: slurm
use-conda: True
conda-prefix: /wrk/guyer/snakemaking/conda
latency-wait: 90
default-resources:
  - mem=1mb
  - slurm_partition="batch"
  - runtime=240
  - constraint="noht"
