fipy_url: "https://github.com/usnistgov/fipy.git"

fipy_revs:
# - "d8a569e79"
- "371d28468" # patched "62cbf2211"
# - "ef3db887e" # patched "b873c7e3f"
# - "f715725b4" # patched "2054173bf"
# - "742c901e9" # patched "36bff3800"
- "a5f233aa7" # patched "2c7ac213b"

replicate: 5

nx:
  min: 16
  max: 2048
  steps: 8

suites:
  "petsc":
    tasks:
      min: 1
      max: 128
      steps: 8
  "no-pysparse":
    tasks:
      min: 1
      max: 128
      steps: 8
  "pysparse":
  "scipy":

totaltime: 8.

benchmark: manufactured_solutions
