simulations: "config/all_permutations.csv"

fipy_url: "https://github.com/usnistgov/fipy.git"

fipy_revs:
# - "d8a569e79"
# - "371d28468" # patched "62cbf2211"
# - "ef3db887e" # patched "b873c7e3f"
# - "f715725b4" # patched "2054173bf"
# - "742c901e9" # patched "36bff3800"
- "a5f233aa7" # patched "2c7ac213b"

replicate: 1

nx:
  min: 512
  max: 512
  steps: 1

suites:
  "petsc":
  "no-pysparse":
  "pysparse":
  "scipy":

totaltime: 0.5

benchmarks:
  manufactured_solutions:
    dimension: 2
