fipy_url: "https://github.com/usnistgov/fipy.git"

fipy_rev:
# - "d8a569e79"
# - "371d28468" # patched "62cbf2211"
# - "ef3db887e" # patched "b873c7e3f"
# - "f715725b4" # patched "2054173bf"
# - "742c901e9" # patched "36bff3800"
- "a5f233aa7" # patched "2c7ac213b"

replicate: 1
suite:
  "petsc":
    task:
      start: 1
      stop: 64
      num: 7
      base: 2
      dtype: int
Lx: 960
dx: 0.5
dt: 0.15
t_max: 1500
r0: 8
view: False
benchmark: dendrite-1D

simulation:
  scan_dx:
    dx:
      start: 0.1
      stop: 2.
      num: 5
      base: 10
  scan_dt:
    dt:
      start: 0.1
      stop: 0.7
      num: 10
      base: 10
  scan_solver:
    t_max: 100
    solver: all
    preconditioner: all
    task: 1
