printshellcmds: True
jobs: 64
executor: slurm
use-conda: True
conda-prefix: /toolbox/guyer/snakemaking/conda
latency-wait: 90
default-resources:
  - mem=1mb
  - slurm_partition="faster"
  - runtime=120
set-resources:
  solve:
    tasks: 64
